# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: python -m isort .
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: python -m black .
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: python -m flake8 .
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: python -m mypy dummit/
    types: [python]
    require_serial: true
    files: ^dummit/
    pass_filenames: false

  # - id: pytest
  #   name: pytest
  #   stages: [commit]
  #   language: system
  #   entry: python -m pytest dummit/
  #   types: [python]
  #   pass_filenames: false
  #   files: ^dummit/

  # - id: pytest-cov
  #   name: pytest
  #   stages: [push]
  #   language: system
  #   entry: python -m  pytest --cov --cov-fail-under=100
  #   types: [python]
  #   pass_filenames: false
